/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import AppFunction.ExFunction;
import AppFunction.SalerFunction;
import AppFunction.UserLog;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class JISalerManage extends javax.swing.JInternalFrame {
    public DefaultTableModel tableModel = new DefaultTableModel();
    public AppFunction.ExFunction exFunc = new ExFunction();
    public AppFunction.SalerFunction salerFunc = new SalerFunction();
    
    /**
     * Creates new form JISalerManage
     */
    public JISalerManage() {
        initComponents();
        this.setResizable(true);
        this.setMinimumSize(new Dimension(855,555));
        this.setSize(getMaxWidth(), getMaxHeight());
        //Create Bill
        salerFunc.viewItemToTable(jTable_Items);
        salerFunc.setDataToCombobox(cmbCategories, "Categories",0);
        salerFunc.setDataToCombobox(cmbCust, "Customers",0);
        txtToday.setText(exFunc.getToday("dd/MM/yyyy"));
        txtBill_Id.setText(String.valueOf(salerFunc.getIdentityId("Bills")));
        txtUsername.setText(View.JIFrameUserLogin.getUserLog().getUserid()+" "+View.JIFrameUserLogin.getUserLog().getUsername());
        //Customer
        salerFunc.viewCust(jTable_Cust);
        //Bill List
        salerFunc.viewBillList(jTable_BillList);
        
    }
    public int getMaxWidth() {
          return GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().width;
     }
     public int getMaxHeight() {
         return GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().height;
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogViewItemsBills = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableViewItemsBills = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTotalPrice_ViewItemBills = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Bill = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbCust = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        txtBill_Id = new javax.swing.JTextField();
        txtUsername = new javax.swing.JLabel();
        txtToday = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Items = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtItemName = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbCategories = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txtItemId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtBillId_Bills = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_BillList = new javax.swing.JTable();
        jDateFrom = new com.toedter.calendar.JDateChooser();
        jDateTo = new com.toedter.calendar.JDateChooser();
        txtSalerId_Bills = new javax.swing.JTextField();
        txtCustId_Bills = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCust_Id = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtCust_Name = new javax.swing.JTextField();
        cmbCust_Gender = new javax.swing.JComboBox<>();
        txtCust_Tel = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCust_Adress = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_Cust = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jTableViewItemsBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane6.setViewportView(jTableViewItemsBills);

        jButton12.setText("Cancel Selected Items");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Cancel All");

        jLabel7.setText("Total Price:");

        txtTotalPrice_ViewItemBills.setText("$");

        javax.swing.GroupLayout jDialogViewItemsBillsLayout = new javax.swing.GroupLayout(jDialogViewItemsBills.getContentPane());
        jDialogViewItemsBills.getContentPane().setLayout(jDialogViewItemsBillsLayout);
        jDialogViewItemsBillsLayout.setHorizontalGroup(
            jDialogViewItemsBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
            .addGroup(jDialogViewItemsBillsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalPrice_ViewItemBills, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDialogViewItemsBillsLayout.setVerticalGroup(
            jDialogViewItemsBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogViewItemsBillsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogViewItemsBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotalPrice_ViewItemBills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialogViewItemsBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
        );

        setTitle("Saler");
        setToolTipText("");

        jPanel2.setPreferredSize(new java.awt.Dimension(635, 615));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill"));

        jTable_Bill.setAutoCreateRowSorter(true);
        jTable_Bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Category", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable_Bill);

        jButton2.setText("Del Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Bill ID:");

        jLabel3.setText("Saler:");

        jLabel4.setText("Date:");

        jLabel5.setText("Total Price:");

        jLabel6.setText("Customer:");

        cmbCust.setEditable(true);
        cmbCust.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtBill_Id.setEditable(false);
        txtBill_Id.setText("0");

        txtUsername.setText("Username");

        txtToday.setText("00/00/0000");

        txtTotalPrice.setText("$0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbCust, 0, 240, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalPrice)
                            .addComponent(txtUsername)
                            .addComponent(txtToday)
                            .addComponent(txtBill_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBill_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsername))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtToday))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalPrice))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Items"));

        jTable_Items.setAutoCreateRowSorter(true);
        jTable_Items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Category", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable_Items);

        jButton1.setText("Add >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText(" Item Name:");

        cmbCategories.setEditable(true);
        cmbCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        jLabel22.setText("Category:");

        jLabel9.setText("Item ID:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel22)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtItemId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCategories, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                            .addComponent(txtItemName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Create Bill", jPanel2);

        jLabel10.setText("Bill ID:");

        jLabel11.setText("Saler:");

        jLabel12.setText("Customer:");

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setText("From:");

        jLabel14.setText("To:");

        jButton6.setText("View Items");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cancel");

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        jTable_BillList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jTable_BillList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BillListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_BillList);

        jDateFrom.setDateFormatString("yyyy-MM-dd");

        jDateTo.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBillId_Bills, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtSalerId_Bills)
                    .addComponent(txtCustId_Bills))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jDateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(328, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel13)
                        .addComponent(txtBillId_Bills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtSalerId_Bills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtCustId_Bills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton6)
                        .addComponent(jButton7)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bills", jPanel1);

        jLabel17.setText("Customer ID:");

        jLabel18.setText("Customer Name:");

        jLabel19.setText("Gender:");

        jLabel20.setText("Tel:");

        jLabel21.setText("Adress:");

        cmbCust_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Male", "Female" }));

        txtCust_Adress.setColumns(20);
        txtCust_Adress.setRows(5);
        jScrollPane4.setViewportView(txtCust_Adress);

        jTable_Cust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jTable_Cust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CustMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable_Cust);

        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Add new");

        jButton10.setText("Edit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Clear");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCust_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jButton8)
                            .addGap(7, 7, 7)
                            .addComponent(jButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton11))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCust_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(txtCust_Name))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCust_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(txtCust_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCust_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21)
                            .addComponent(txtCust_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cmbCust_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customers", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String _mycondition = "";
       if(txtItemId.getText().isEmpty()&&txtItemName.getText().isEmpty()&&cmbCategories.getSelectedItem().toString() == "All"){
           _mycondition = "";
       }else{
            _mycondition = " WHERE";
       }
        if(!txtItemId.getText().isEmpty()){
            _mycondition += " item_Id = "+txtItemId.getText();
            if(!txtItemName.getText().isEmpty()||cmbCategories.getSelectedItem().toString() != "All"){
                _mycondition += " AND";
            }
        }
        if(!txtItemName.getText().isEmpty()){
            _mycondition += " item_Name = '"+txtItemName.getText()+"'";
            if(cmbCategories.getSelectedItem().toString() != "All"){
                _mycondition += " AND";
            }
        }
        if(cmbCategories.getSelectedItem().toString() != "All"){
            int _catg_id = salerFunc.getIdByName("Categories", "category_Name", cmbCategories.getSelectedItem().toString());
            _mycondition += " category_Id = "+_catg_id;
            JOptionPane.showMessageDialog(null, _catg_id+";"+_mycondition);
        }
        salerFunc.searchItem(jTable_Items, _mycondition);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        salerFunc.addItemToBill(jTable_Items, jTable_Bill);
        txtTotalPrice.setText("$"+String.valueOf(salerFunc.totalPrice(jTable_Bill,4)));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Date thistime = new Date(System.currentTimeMillis());
        int billid = Integer.parseInt(txtBill_Id.getText());
        int userid = View.JIFrameUserLogin.getUserLog().getUserid();
        int custid = salerFunc.getIdByName("Customers", "cust_Name", cmbCust.getSelectedItem().toString());
        Date billdate = Date.valueOf(exFunc.getToday("yyyy-MM-dd"));
        String billtype = "export";
        salerFunc.submitBill(userid,custid,billdate, billtype);
        salerFunc.submitBillDetail(jTable_Bill, billid);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int _confirm = JOptionPane.showConfirmDialog(null, "Are you sure delete items from the bill?");
        if(_confirm == JOptionPane.YES_OPTION){
            salerFunc.delRowInTable(jTable_Bill);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String _mycondition = "";
        if(txtCust_Id.getText().isEmpty()
            && txtCust_Name.getText().isEmpty()
            && txtCust_Tel.getText().isEmpty()
            && txtCust_Adress.getText().isEmpty()
            && cmbCust_Gender.getSelectedItem().toString() == "All"){
            _mycondition = "";
        }else{
             _mycondition = " WHERE";
        }
        if(!txtCust_Id.getText().isEmpty()){
            _mycondition += " cust_Id = "+txtCust_Id.getText();
            if(!txtCust_Name.getText().isEmpty()
                    || !txtCust_Tel.getText().isEmpty()
                    || !txtCust_Adress.getText().isEmpty()
                    || cmbCust_Gender.getSelectedItem().toString() != "All"){
                _mycondition += " AND";
            }
        }
        if(!txtCust_Name.getText().isEmpty()){
            _mycondition += " cust_Name = '"+txtCust_Name.getText()+"'";
            if(!txtCust_Tel.getText().isEmpty()
                    || !txtCust_Adress.getText().isEmpty()
                    || cmbCust_Gender.getSelectedItem().toString() != "All"){
                _mycondition += " AND";
            }
        }
        if(!txtCust_Tel.getText().isEmpty()){
            _mycondition += " cust_Tel = '"+txtCust_Tel.getText()+"'";
            if(!txtCust_Adress.getText().isEmpty()
                    || cmbCust_Gender.getSelectedItem().toString() != "All"){
                _mycondition += " AND";
            }
        }
        if(!txtCust_Adress.getText().isEmpty()){
            _mycondition += " cust_Adress = '"+txtCust_Adress.getText()+"'";
            if(cmbCust_Gender.getSelectedItem().toString() != "All"){
                _mycondition += " AND";
            }
        }
        if(cmbCust_Gender.getSelectedItem().toString() != "All"){
            _mycondition += " cust_Gender = '"+cmbCust_Gender.getSelectedItem().toString()+"'";
        }
        salerFunc.searchCust(jTable_Cust, _mycondition);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable_CustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CustMouseClicked
        // TODO add your handling code here:
        salerFunc.getTableToTextField(jTable_Cust, 0, txtCust_Id);
        salerFunc.getTableToTextField(jTable_Cust, 1, txtCust_Name);
        salerFunc.getTableToCombobox(jTable_Cust, 2, cmbCust_Gender);
        salerFunc.getTableToTextField(jTable_Cust, 3, txtCust_Tel);
        salerFunc.getTableToTextField(jTable_Cust, 4, txtCust_Adress);
    }//GEN-LAST:event_jTable_CustMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int custid = Integer.parseInt(txtCust_Id.getText());
        String custname = txtCust_Name.getText();
        String custgender = cmbCust_Gender.getSelectedItem().toString();
        String custtel = txtCust_Tel.getText();
        String custadress = txtCust_Adress.getText();
        salerFunc.editCust(custid, custname, custgender, custtel, custadress);
        salerFunc.viewCust(jTable_Cust);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        txtCust_Id.setText("");
        txtCust_Name.setText("");
        txtCust_Tel.setText("");
        txtCust_Adress.setText("");
        cmbCust_Gender.setSelectedItem("All");
        salerFunc.viewCust(jTable_Cust);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Date datefrom = Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(jDateFrom.getDate()));
        Date dateto = Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(jDateTo.getDate()));
        String _mycondition = "";
        if(txtBillId_Bills.getText().isEmpty()
            && txtSalerId_Bills.getText().isEmpty()
            && txtCustId_Bills.getText().isEmpty()
            && datefrom == Date.valueOf(exFunc.getToday("yyyy-MM-dd"))
            && dateto == Date.valueOf(exFunc.getToday("yyyy-MM-dd"))){
            _mycondition = "";
        }else{
             _mycondition = " WHERE";
        }
        
        if(!txtBillId_Bills.getText().isEmpty()){
            _mycondition += " bill_Id = "+txtBillId_Bills.getText();
            if(!txtSalerId_Bills.getText().isEmpty()
                    || !txtCustId_Bills.getText().isEmpty()
                    || datefrom != Date.valueOf(exFunc.getToday("yyyy-MM-dd"))
                    || dateto != Date.valueOf(exFunc.getToday("yyyy-MM-dd"))){
                _mycondition += " AND";
            }
        }
        if(!txtSalerId_Bills.getText().isEmpty()){
            _mycondition += " user_Id = "+txtSalerId_Bills.getText();
            if(!txtCustId_Bills.getText().isEmpty()
                    || datefrom != Date.valueOf(exFunc.getToday("yyyy-MM-dd"))
                    || dateto != Date.valueOf(exFunc.getToday("yyyy-MM-dd"))){
                _mycondition += " AND";
            }
        }
        if(!txtCustId_Bills.getText().isEmpty()){
            _mycondition += " cust_Id = "+txtCustId_Bills.getText();
            if(datefrom != Date.valueOf(exFunc.getToday("yyyy-MM-dd"))
                    || dateto != Date.valueOf(exFunc.getToday("yyyy-MM-dd"))){
                _mycondition += " AND";
            }
        }
        if(datefrom != Date.valueOf(exFunc.getToday("yyyy-MM-dd"))
                || dateto != Date.valueOf(exFunc.getToday("yyyy-MM-dd"))){
            JOptionPane.showMessageDialog(null, datefrom);
            _mycondition += " bill_Date BETWEEN '"+datefrom+"' AND '"+dateto+"'";
        }
        salerFunc.searchBillList(jTable_BillList, _mycondition);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jDialogViewItemsBills.setVisible(true);
        jDialogViewItemsBills.setBounds(0, 0, getMaxWidth()/2,getMaxHeight()/2);
        salerFunc.viewItemsByBillId(jTableViewItemsBills, Integer.parseInt(txtBillId_Bills.getText()));
        txtTotalPrice_ViewItemBills.setText("$"+String.valueOf(salerFunc.totalPrice(jTableViewItemsBills, 4)));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void jTable_BillListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BillListMouseClicked
        // TODO add your handling code here:
        salerFunc.getTableToTextField(jTable_BillList, 0, txtBillId_Bills);
        txtSalerId_Bills.setText(String.valueOf(salerFunc.getIdByName("Users", "user_Name", salerFunc.getTabledata(jTable_BillList, 1))));
        txtCustId_Bills.setText(String.valueOf(salerFunc.getIdByName("Customers", "cust_Name", salerFunc.getTabledata(jTable_BillList, 2))));
    }//GEN-LAST:event_jTable_BillListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCategories;
    private javax.swing.JComboBox<String> cmbCust;
    private javax.swing.JComboBox<String> cmbCust_Gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateFrom;
    private com.toedter.calendar.JDateChooser jDateTo;
    private javax.swing.JDialog jDialogViewItemsBills;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableViewItemsBills;
    private javax.swing.JTable jTable_Bill;
    private javax.swing.JTable jTable_BillList;
    private javax.swing.JTable jTable_Cust;
    private javax.swing.JTable jTable_Items;
    private javax.swing.JTextField txtBillId_Bills;
    private javax.swing.JTextField txtBill_Id;
    private javax.swing.JTextField txtCustId_Bills;
    private javax.swing.JTextArea txtCust_Adress;
    private javax.swing.JTextField txtCust_Id;
    private javax.swing.JTextField txtCust_Name;
    private javax.swing.JTextField txtCust_Tel;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtSalerId_Bills;
    private javax.swing.JLabel txtToday;
    private javax.swing.JLabel txtTotalPrice;
    private javax.swing.JLabel txtTotalPrice_ViewItemBills;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
